# Generated by Django 5.1.7 on 2025-07-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('inventory_count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_app.merchant')),
            ],
        ),
    ]
