# Generated by Django 5.1.7 on 2025-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_transaction_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
